version: "3.9"
services:
  mongo:
    image: mongo:7.0
    container_name: mile-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASS}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
      MONGO_USERNAME: ${MONGO_APP_USER}
      MONGO_PASSWORD: ${MONGO_APP_PASS}
    volumes:
      - ./db/data:/data/db
      - ./db/init:/docker-entrypoint-initdb.d:ro
      - ./db/indexes.js:/docker-entrypoint-initdb.d/../indexes.js:ro

  mongo-express:
    image: mongo-express:1.0.2
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASS}
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo
